  name: Deploy Site

  on:
    workflow_dispatch: # Allows manual triggering of the workflow
    repository_dispatch: # Allows external services to trigger the workflow
      types: [prismic-update]

  jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        # Add steps to build your site
        # - name: Install dependencies
        #   run: npm install
        # - name: Build site
        #   run: npm run build

        - name: Publish to Cloudflare Workers
          run: npm run deploy
          env:
            CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
